[project]
name = "ziggy-pydust-template"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    {name = "Fulcrum Inc.", email = "hello@fulcrum.so"},
]
requires-python = "<4.0,>=3.11"
dependencies = []

[dependency-groups]
dev = [
    "ziggy-pydust==0.25.1",
    "pytest<9.0.0,>=8.0.0",
    "ruff<1.0.0,>=0.12.0",
]

[build-system]
requires = ["pdm-backend", "ziggy-pydust==0.25.1"]
build-backend = "pdm.backend"

[tool.pdm.build]
custom-hook = "build.py"
includes = [
    "src/",
    "fibonacci",
    "fibonacci/*.so",
    "fibonacci/*.pyi",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["F", "E", "W", "UP", "I001", "I002"]

[[tool.pydust.ext_module]]
name = "fibonacci._lib"
root = "src/fib.zig"