name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  actions: read
  contents: read

env:
  PYTHON_VERSION: "3.13"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Build
        run: uv build

      - name: Ruff
        run: uv run ruff check .
      - name: Ruff format
        run: uv run ruff format --check .
      - name: Pytest
        run: uv run pytest
      - name: Check stubs
        run: uv run python -m ziglang build generate-stubs -Dcheck-stubs=true
